import type { SyntaxHighlighterProps } from "react-syntax-highlighter";

type SyntaxStyle = NonNullable<SyntaxHighlighterProps["style"]>;

/** Fundi3 brand theme for fenced code blocks — mirrors the Sandpack `fundi3Theme` palette. */
export const fundi3CodeTheme: SyntaxStyle = {
  'pre[class*="language-"]': {
    color: "#F5FAF7",
    background: "transparent",
    fontFamily: "var(--font-jetbrains-mono), monospace",
    fontSize: "0.8125rem",
    lineHeight: "1.65",
    margin: 0,
    padding: 0,
    whiteSpace: "pre",
  },
  'code[class*="language-"]': {
    color: "#F5FAF7",
    background: "transparent",
    fontFamily: "var(--font-jetbrains-mono), monospace",
    fontSize: "0.8125rem",
    lineHeight: "1.65",
  },
  ':not(pre) > code[class*="language-"]': {
    color: "#9FE1CB",
    background: "rgba(29, 158, 117, 0.12)",
    padding: "0.15em 0.4em",
    borderRadius: "0.35rem",
  },
  comment: { color: "#4A6358", fontStyle: "italic" },
  prolog: { color: "#4A6358", fontStyle: "italic" },
  doctype: { color: "#4A6358", fontStyle: "italic" },
  cdata: { color: "#4A6358", fontStyle: "italic" },
  punctuation: { color: "#9FE1CB" },
  property: { color: "#9FE1CB" },
  tag: { color: "#9FE1CB" },
  boolean: { color: "#9FE1CB" },
  number: { color: "#9FE1CB" },
  constant: { color: "#9FE1CB" },
  symbol: { color: "#9FE1CB" },
  deleted: { color: "#9FE1CB" },
  "attr-name": { color: "#9FE1CB" },
  selector: { color: "#FAC775" },
  string: { color: "#FAC775" },
  char: { color: "#FAC775" },
  builtin: { color: "#FAC775" },
  inserted: { color: "#FAC775" },
  url: { color: "#FAC775" },
  "attr-value": { color: "#FAC775" },
  operator: { color: "rgba(245, 250, 247, 0.85)" },
  entity: { color: "rgba(245, 250, 247, 0.85)" },
  atrule: { color: "#1D9E75" },
  keyword: { color: "#1D9E75" },
  function: { color: "#EF9F27" },
  "class-name": { color: "#EF9F27" },
  regex: { color: "#EF9F27" },
  important: { color: "#EF9F27", fontWeight: "bold" },
  variable: { color: "#EF9F27" },
  bold: { fontWeight: "bold" },
  italic: { fontStyle: "italic" },
};
